---
apiVersion: v1
kind: Service
metadata:
  name: foodmag-app-db
  namespace: stateful-app-dev
  labels:
    app: foodmag-app-db
    env: dev
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
    app: foodmag-app-db
    env: dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foodmag-app-db
  namespace: stateful-app-dev
spec:
  selector:
    matchLabels:
      app: foodmag-app-db
      env: dev
  serviceName: foodmag-app-db-service
  replicas: 1
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: foodmag-app-db-pvc
      labels:
        app: foodmag-app-db
        env: dev
    spec:
      containers:
        - name: foodmag-app-db
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: foodmag-app-db
          env:
            - name: POSTGRES_DB
              value: foodmagappdb
            - name: POSTGRES_USER
              value: foodmagapp
            - name: POSTGRES_PASSWORD
              value: foodmagpassword
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: foodmag-app-db-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: foodmag-app-db-pvc
        labels:
          app: foodmag-app-db
          env: dev
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "storage-for-dev-and-test"
        resources:
          requests:
            storage: 1Gi
